name: ZeehoDiag
options:
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "14.0"
settings:
  base:
    CODE_SIGNING_ALLOWED: "NO"
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGN_IDENTITY: ""
targets:
  ZeehoDiag:
    type: application
    platform: iOS
    sources:
      - path: App/Sources
      - path: App/Resources
      - path: App/Info.plist
        buildPhase: none
    settings:
      base:
        PRODUCT_NAME: ZeehoDiag
        PRODUCT_BUNDLE_IDENTIFIER: com.zeeho.diag
        INFOPLIST_FILE: App/Info.plist
        TARGETED_DEVICE_FAMILY: "1"
        ENABLE_BITCODE: "NO"
        IPHONEOS_DEPLOYMENT_TARGET: "14.0"